version: "3.7"
services:
  wordpress_phpunit:
    image: "chriszarate/wordpress-phpunit:6.0.6"
    volumes:
      - ".:/app"
      - "testsuite:/tmp"
  mysql_phpunit:
    image: "mariadb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_test"
volumes:
  testsuite: {}
